baseurl = "https://fryl.dev/"
title = "fryl.dev"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
    # Cutting off the page title to two chars for mobile (console-demo -> co)
    titleCutting = true
    navTitle = "root@fryl.dev"

    # Set the animation style -- https://animate.style/
    # To disable animations, please remove or comment animationStyle parameter
    animateStyle = "animated zoomIn fast"

    [[params.navlinks]]
        name = "Twitter"
        url = "https://x.com/0xFryl"

    [[params.navlinks]]
        name = "Bluesky"
        url = "https://bsky.app/profile/fryl.dev"
